import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/tokyonight_storm.toml"
  "~/.config/alacritty/themes/tokyonight_storm.toml",

]

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[shell]
# args = ["-l", "-c", "tmux attach || tmux new -s main"]
program = "zsh"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.97
title = "Alacritty"
option_as_alt = "OnlyLeft"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

